version: "3.7"

services:

  db:
    image: mariadb
    environment:
      MARIADB_ROOT_PASSWORD: root
    volumes:
      - ./data:/var/lib/mysql
    ports:
      - 3306:3306

  adminer:
    image: adminer
    restart: always
    depends_on:
      - db
    ports:
      - 8081:8080
    environment:
      - MYSQL_ROOT_PASSWORD=root